### PR TITLE
use dns cache

### PR DESCRIPTION
**Pull request by genofire**
maybe later deactivate dhcp dnsserver entry by gw/vpn (ansible)

### CODE REVIEW

**Comment by jplitza** [comment]
There already is a branch called v2018.1 that has the site_seed, please remove it from the PR.

Also, this will use almost 500 KB of RAM. Are we sure all nodes can handle that?

**Comment by jplitza** [comment]
Also, having multiple names for next_node is not yet supported (see freifunk-gluon/gluon#1288) and will only make it into 2018.1 if at all.

**Comment by genofire** [comment]
okay for `next_node` - i choose `node.ffhb.de`, i believe it is most used - if multiple names is supported, we could use `node.bremen.freifunk.net` again

With the cache size, i do not know. But i really like to have `node.ffhb.de` without internet connection - it there would be a cache of `3` it would be enough for me.

**Comment by genofire** [comment]
Are 10KB of RAM okay? @jplitza

**Comment by jplitza** [comment]
Das Treffen hat das Feature für gut befunden und 500 Einträge/50 KB RAM als guten Kompromiss akzeptiert → Merge.

**Pull request merged**
